services:
  #Contenedor de la base de datos
  sistema:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${NAME_DATABASE}
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DATABASE}
    volumes:
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
      #Para proteger los datos guardados en la DB incluso si se borra el contenedor
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  #Contenedor de phpMyAdmin (Para ver la tabla de la base de datos)
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_web
    restart: always
    ports:
      - "8081:80"            #Puerto para acceder a la base de datos
    environment:
      PMA_HOST: sistema
      MYSQL_ROOT_PASSWORD: ${PASSWORD_DATABASE}
    depends_on:
      - sistema

  #Contenedor para el servidor web (PHP)
  web:
    image: php:8.2-apache
    container_name: php_web
    depends_on:
      - sistema
    volumes:
      - ./PHP:/var/www/html
      - ./shared:/var/www/html/shared
    ports:
      - "8080:80"
    # Instalamos la extensiÃ³n PDO para MySQL dentro del contenedor
    command: >
      sh -c "docker-php-ext-install pdo pdo_mysql && apache2-foreground"
  
  #Contenedor para los reportes de Python
  reporte:
    build:
      context: ./Script
      dockerfile: Dockerfile
    container_name: python_script
    depends_on:
      - sistema
    volumes:
      - ./shared:/app/shared

#Crea un espacio de almacenamiento en la PC para proteger los datos incluso si se borra el contenedor
volumes:
  db_data: